name: Alex
version: ${project.version}
description: o.o

main: uk.thinkofdeath.minecraft.alex.AlexPlugin

commands:
  gamemode: {}
  give: {}
  gm: {}
  gma: {}
  gmc: {}
  gms: {}
  gmsp: {}
  i: {}
  nick: {}
  time: {}
  worlds: {}
